### ISSUE TITLE
Syncing error

### ISSUE THREAD

**Issue by meltausorion** [airalab/substrate-node-robonomics#1]
Unable to complete synchronization. There is always an error on the unit concrete 76500. H
ash that was given is different from what was expected. In the logs "Storage root must match that calculated."but I don't see the tools for that.

Version 0.2.1

![robonomic](https://user-images.githubusercontent.com/13775964/51275829-95afdd00-1a05-11e9-9f4f-85dfb8b9bf4b.png)

**Comment by akru** [comment]
Thank you for reporting! As I see it’s a part of substrate storage module in heavy development. Could you rollback to 0.1.0, this version have less performance and bit large chain size but more stable.

**Comment by akru** [comment]
Error from pic1 is catched because runtime isn’t builded, please build it via ‘build.sh’ script (it require wasm-gc dependency).
