### ISSUE TITLE
Filed sync v0.8.0

### ISSUE THREAD

**Issue by meltausorion** [airalab/substrate-node-robonomics#16]
After update on v0.8.0 not syncing.

https://pastebin.com/rRsgWfqk

![0003](https://user-images.githubusercontent.com/13775964/54365952-61be0480-46a2-11e9-99f8-e06e89becf69.png)

**Comment by akru** [comment]
How to reproduce this error step by step?

Could you try to use latest release

**Comment by meltausorion** [comment]
Unchanged.
https://pastebin.com/m8Eia8WE

![0004](https://user-images.githubusercontent.com/13775964/54409878-96ba6d80-471b-11e9-8ca0-635aed26ebb8.png)

**Comment by akru** [comment]
Are you clean .local/share/robonomics before launch?

**Comment by meltausorion** [comment]
I use not default dir base, but cneal this dir it helped. Thanks.
