### ISSUE TITLE
Fail sync and startup v0.8.1

### ISSUE THREAD

**Issue by meltausorion** [airalab/substrate-node-robonomics#18]
After update on v0.8.1 and new sync. Synchronization does not complete until the end. If you restart, it does not start with an error:
`stack backtrace:
   0: substrate_panic_handler::set::{{closure}}::h8c172536ddeed52c (0x5607e0077030)
   1: std::panicking::rust_panic_with_hook::h744417edfe714d72 (0x5607e01b21e9)
             at src/libstd/panicking.rs:482
   2: std::panicking::continue_panic_fmt::h3557b3c3fa21b47b (0x5607e01b1c91)
             at src/libstd/panicking.rs:385
   3: rust_begin_unwind (0x5607e01b1b75)
             at src/libstd/panicking.rs:312
   4: core::panicking::panic_fmt::h74ee8034b317ceed (0x5607e01cc85c)
             at src/libcore/panicking.rs:85
   5: core::result::unwrap_failed::h2f330128db75f64a (0x5607df7b22f9)
   6: <substrate_state_machine::ext::Ext<'a, H, B, T> as substrate_state_machine::Externalities<H>>::storage::h5d825c512f635bc5 (0x5607df8a2a84)
   7: <std::thread::local::LocalKey<T>>::with::h9f5371b40d21a095 (0x5607e0058d79)
   8: sr_io::read_storage::h07e4931de7237377 (0x5607e005868b)
   9: <(R, S) as srml_session::OnSessionChange<T>>::on_session_change::h3cfc60f9d42a1790 (0x5607df932502)
  10: <(O, P, Q, R, S, T, U, V, W, X, Y, Z) as sr_primitives::traits::OnFinalise<Number>>::on_finalise::h864a1253543c4598 (0x5607df93b55e)
  11: <srml_executive::Executive<System, Block, Context, Payment, AllModules>>::execute_block::h2d94eb8736b42088 (0x5607df945dfe)
  12: robonomics_runtime::api::dispatch::h624caf9d0d3a021c (0x5607df90f035)
  13: std::panicking::try::do_call::h16d544c6ead56926 (0x5607df5e00b1)
  14: __rust_maybe_catch_panic (0x5607e01b80c9)
             at src/libpanic_unwind/lib.rs:92
  15: substrate_executor::native_executor::safe_call::h81306eea0bdc92f8 (0x5607df6ac2d2)
  16: <std::thread::local::LocalKey<T>>::with::hc9c70572b5c96012 (0x5607df4875bd)
  17: <robonomics::service::Executor as substrate_executor::native_executor::NativeExecutionDispatch>::dispatch::h4271ddecaa373e2d (0x5607df68b8ec)
  18: <std::thread::local::LocalKey<T>>::with::h290e7f4fff2e6c93 (0x5607df46df07)
  19: <substrate_state_machine::StateMachine<'a, H, B, T, Exec>>::execute_aux::ha2e9fe2d6eaa71e1 (0x5607df514f15)
  20: <substrate_state_machine::StateMachine<'a, H, B, T, Exec>>::execute_call_with_native_else_wasm_strategy::hc2a4ec9934383ccf (0x5607df548cd2)
  21: <substrate_state_machine::StateMachine<'a, H, B, T, Exec>>::execute_using_consensus_failure_handler::he84202adce92d3e5 (0x5607df54300b)
  22: <substrate_client::call_executor::LocalCallExecutor<B, E> as substrate_client::call_executor::CallExecutor<Block, substrate_primitives::hasher::blake2::Blake2Hasher>>::call_at_state::hae616b5e2153243c (0x5607df5c6214)
  23: <substrate_client::client::Client<B, E, Block, RA>>::lock_import_and_run::{{closure}}::hfc8892df172ec1b1 (0x5607df8f03e6)
  24: <substrate_client::client::Client<B, E, Block, RA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::h011036f8f4e4937b (0x5607df8aaca6)
  25: <substrate_finality_grandpa::import::GrandpaBlockImport<B, E, Block, RA, PRA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::ha8d64fa10d7ae4be (0x5607df64c87f)
  26: <substrate_consensus_common::import_queue::BlockImportWorker<B, V>>::import_a_batch_of_blocks::hd6dd8f4565ba6fb0 (0x5607df44825c)
  27: std::sys_common::backtrace::__rust_begin_short_backtrace::h695cdc456337430b (0x5607df65bb8e)
  28: std::panicking::try::do_call::h0b6aef095d7c20fa (0x5607df5e006d)
  29: __rust_maybe_catch_panic (0x5607e01b80c9)
             at src/libpanic_unwind/lib.rs:92
  30: <F as alloc::boxed::FnBox<A>>::call_box::h818e31113346bb43 (0x5607df6cbe9e)
  31: <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::h2263113ac6678036 (0x5607e01b743d)
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/liballoc/boxed.rs:744
      std::sys_common::thread::start_thread::h7f66efdea8634396
             at src/libstd/sys_common/thread.rs:14
      std::sys::unix::thread::Thread::new::thread_start::h6fb76bcf544b6181
             at src/libstd/sys/unix/thread.rs:81
  32: start_thread (0x7feb141cf6da)
  33: __clone (0x7feb13ce088e)
  34: <unknown> (0x0)

Thread 'ImportQueueWorker' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Database missing expected key: 0x6a457f7d0db6720a7e06028911d43c9f6a50e81dfa24f28bb9d9e5ea3c1a0c9b"', src/libcore/result.rs:997

This is a bug. Please report it at:

	https://github.com/airalab/substrate-node-robonomics/issues
`

**Comment by akru** [comment]
Duplicate #13
