### ISSUE TITLE
The node is killed by zsh after some time passed

### ISSUE THREAD

**Issue by Vourhey** [airalab/substrate-node-robonomics#34]
I noticed a weird behavior. 
I launch the robonomics node with:
```
./robonomics --name vourhey
```
and leave it as it is.
But after some time passed there is no my node on the telemetry website. So i go to console and I see
```
zsh: killed     ./robonomics --name vourhey
```
with no errors. It has happend few time already. So I don't know if it is a bug or my virtual machine doesn't have enough resources. Could you give a hint what could be the cause?

**Comment by akru** [comment]
Hello @Vourney, check your RAM size please.

**Comment by Vourhey** [comment]
It's 4Gb and no swap file
Currently it's working and there are 2Gb of free memory

**Comment by akru** [comment]
What’s about dmesg log?

**Comment by Vourhey** [comment]
The last message is 
```
[1262320.621442] Out of memory: Kill process 23983 (robonomics) score 844 or sacrifice child
[1262320.621636] Killed process 23983 (robonomics) total-vm:9187676kB, anon-rss:3399928kB, file-rss:0kB, shmem-rss:0kB
[1262320.826507] oom_reaper: reaped process 23983 (robonomics), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

**Comment by Vourhey** [comment]
It happend again with the same dmesg log messages.
I have 4Gb of ram and no swap file. Could it be the cause?

**Comment by akru** [comment]
It looks like your VM feature, could you monitor resource consumption during usage?

Currently I use Robonomics in same time as polkadot node on 2G VPS in Heitzner cloud without getting OOM.
