### ISSUE TITLE
Cannot build (tag) v0.13

### ISSUE THREAD

**Issue by emielvanderhoek** [airalab/substrate-node-robonomics#38]
```
   Compiling substrate-ros-msgs v0.1.0 (/rustbuilder/airalab-substrate-node-robonomics/substrate-ros/msgs)
error: proc macro panicked
  --> substrate-ros/msgs/src/lib.rs:21:1
   |
21 | / rosmsg_include!(
22 | |     // standard ros messages
23 | |     std_msgs / UInt64,
24 | |     std_msgs / String,
...  |
62 | |     substrate_ros_msgs / StartLiability,
63 | | );
   | |__^
   |
   = help: message: message substrate_ros_msgs/StartLiability not found in provided directories
           Directories:
           share
           ../src


error: aborting due to previous error
```

**Comment by akru** [comment]
Hello @emielvanderhoek! Yes, this part is on heavy development. But blockchain part is ready for work!

Please use —bin robonomics flag to build binary only.

**Comment by emielvanderhoek** [comment]
@akru could you highlight the required change of the build process in our Dockerfile plz: https://github.com/polkasource/substrate-client/blob/robonomics/Dockerfile

**Comment by emielvanderhoek** [comment]
Likely a change to this line: https://github.com/polkasource/substrate-client/blob/808037150c4649cd5ceb8612969f97e1686d145b/Dockerfile#L30

**Comment by akru** [comment]
Absolutely right, just add “—bin robonomics” to line.

It not looks generic I hope to fix build ASAP. But for temporary usage please build binary directly.

**Comment by emielvanderhoek** [comment]
build succeeded.
