### ISSUE TITLE
Install error: failed to compile `robonomics v0.3.2

### ISSUE THREAD

**Issue by ensrationis** [airalab/substrate-node-robonomics#5]
ens@ens-nuc-worker:~$ cargo install --force --git https://github.com/airalab/substrate-node-robonomics robonomics
    Updating git repository `https://github.com/airalab/substrate-node-robonomics`
  Installing robonomics v0.3.2 (https://github.com/airalab/substrate-node-robonomics#67c179fc)                                                                                                              
    Updating crates.io index
    Updating git repository `https://github.com/paritytech/substrate`                                                                                                                                       
error: failed to compile `robonomics v0.3.2 (https://github.com/airalab/substrate-node-robonomics#67c179fc)`, intermediate artifacts can be found at `/tmp/cargo-installinLvG1`                             

Caused by:
  no matching package named `substrate-client` found
location searched: https://github.com/paritytech/substrate#9edfc244
did you mean: substrate-cli, substrate-client-db
required by package `robonomics v0.3.2 (https://github.com/airalab/substrate-node-robonomics#67c179fc)`
ens@ens-nuc-worker:~$

**Comment by akru** [comment]
Could you check v0.4.0 release?

**Comment by ensrationis** [comment]
Sure, I saw new commit, so I can just repeat quick start? If yes, then we have another problem :)
ens@ens-nuc-worker:~$ cargo install --force --git https://github.com/airalab/substrate-node-robonomics robonomics
    Updating git repository `https://github.com/airalab/substrate-node-robonomics`
error: could not find `robonomics` in https://github.com/airalab/substrate-node-robonomics

**Comment by akru** [comment]
Could you try to install latest rust via https://github.com/paritytech/substrate#61-hacking-on-substrate

**Comment by akru** [comment]
Solved
