### ISSUE TITLE
Thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value

### ISSUE THREAD

**Issue by ensrationis** [airalab/substrate-node-robonomics#6]
Trying to update to 0.6.1 ver with command "cargo install --force --git https://github.com/airalab/substrate-node-robonomics". After succeeded compiling, I tried to run Robonomics node, but unsuccessful with the next log:

ens@ens-nuc-worker:~$ robonomics --name EnsNuc
2019-02-19 23:16:33 Robonomics Node
2019-02-19 23:16:33   version 0.6.1-4474c94-x86_64-linux-gnu
2019-02-19 23:16:33   by Airalab <research@aira.life>, 2018, 2019
2019-02-19 23:16:33 Chain specification: Robonomics
2019-02-19 23:16:33 Node name: EnsNuc
2019-02-19 23:16:33 Roles: FULL
2019-02-19 23:16:34 Loading GRANDPA authorities from genesis on what appears to be first startup.

====================

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}::he1cccc1002712ca3 (0x55e06eaecb60)
   1: std::panicking::rust_panic_with_hook::h8cbdfe43764887be (0x55e06ec22e39)
             at src/libstd/panicking.rs:495
   2: std::panicking::continue_panic_fmt::h3d3c5a833c00a5e1 (0x55e06ec228e1)
             at src/libstd/panicking.rs:398
   3: rust_begin_unwind (0x55e06ec227c5)
             at src/libstd/panicking.rs:325
   4: core::panicking::panic_fmt::h4d67173bc68f6d5a (0x55e06ec3a7bc)
             at src/libcore/panicking.rs:95
   5: core::result::unwrap_failed::h9cfb7bd6fb3064b2 (0x55e06e101019)
   6: <robonomics::service::Factory as substrate_service::components::ServiceFactory>::new_full::h37faad1f2330c92a (0x55e06e0b9b29)
   7: substrate_cli::parse_and_execute::h013ec0cbbefa5dd8 (0x55e06dfea2c3)
   8: robonomics::main::hdda758ca99b2d58b (0x55e06df61522)
   9: std::rt::lang_start::{{closure}}::h8705bcb578cc3f34 (0x55e06e0dbaa2)
  10: std::rt::lang_start_internal::{{closure}}::hdfc28107b5be47c9 (0x55e06ec22762)
             at src/libstd/rt.rs:59
      std::panicking::try::do_call::h69790245ac2d03fe
             at src/libstd/panicking.rs:310
  11: __rust_maybe_catch_panic (0x55e06ec33ab9)
             at src/libpanic_unwind/lib.rs:102
  12: std::panicking::try::h9c1cbc5599e1efbf (0x55e06ec231f3)
             at src/libstd/panicking.rs:289
      std::panic::catch_unwind::h0562757d03ff60b3
             at src/libstd/panic.rs:398
      std::rt::lang_start_internal::h540c897fe52ba9c5
             at src/libstd/rt.rs:58
  13: main (0x55e06df616c1)
  14: __libc_start_main (0x7f57acbc9b96)
  15: _start (0x55e06ddac569)
  16: <unknown> (0x0)

Thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Client(UnknownBlock("State already discarded for Number(0)")), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })', src/libcore/result.rs:1009

This is a bug. Please report it at:

        https://github.com/airalab/substrate-node-robonomics/issues

**Comment by akru** [comment]
Clean up db is required.

**Comment by ensrationis** [comment]
Thanks, @akru , db filepath is: ~/.local/share/robonomics
