### ISSUE TITLE
Thread 'ImportQueueWorker' panicked at 'Storage root must match that calculated.'

### ISSUE THREAD

**Issue by ensrationis** [airalab/substrate-node-robonomics#7]
My worker stack at 3,236 block and start sending me next log:  

10: <std::thread::local::LocalKey<T>>::with::h9647cb3c4037c87d (0x5633a9637649)
  11: substrate_state_machine::execute_aux::h713e3a1faf90c73d (0x5633a94f5ea3)
  12: substrate_state_machine::execute_call_with_native_else_wasm_strategy::hed692ba7d4914492 (0x5633a952dde0)
  13: substrate_state_machine::execute_using_consensus_failure_handler::hc5bdb20d3af9b481 (0x5633a951eb65)
  14: <substrate_client::call_executor::LocalCallExecutor<B, E> as substrate_client::call_executor::CallExecutor<Block, substrate_primitives::hasher::blake2::Blake2Hasher>>::call_at_state::h90e862eefca857ee (0x5633a96fe98b)
  15: <substrate_client::client::Client<B, E, Block, RA>>::lock_import_and_run::{{closure}}::h8f2d827c453f2465 (0x5633a998c19e)
  16: <substrate_client::client::Client<B, E, Block, RA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::h4b77de41b3728cd3 (0x5633a99481c6)
  17: <substrate_finality_grandpa::import::GrandpaBlockImport<B, E, Block, RA, PRA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::heded5e162d0a7ab0 (0x5633a9568a6e)
  18: <substrate_consensus_common::import_queue::BlockImportWorker<B, V>>::import_a_batch_of_blocks::h727a7cfa867194df (0x5633a9995cd0)
  19: std::sys_common::backtrace::__rust_begin_short_backtrace::h6cbe6a2fe31a5a54 (0x5633a949c0ee)
  20: std::panicking::try::do_call::h3f6dcfc92a811645 (0x5633a968af4d)
  21: __rust_maybe_catch_panic (0x5633aa2c2ab9)
             at src/libpanic_unwind/lib.rs:102
  22: <F as alloc::boxed::FnBox<A>>::call_box::hd07c468b6ca4f9e5 (0x5633a979142e)
  23: <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::hece536cf07b94f8d (0x5633aa2b667d)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/liballoc/boxed.rs:683
      std::sys_common::thread::start_thread::h9605a7df0f911844
             at src/libstd/sys_common/thread.rs:24
      std::sys::unix::thread::Thread::new::thread_start::hca8e72c41fa9d291
             at src/libstd/sys/unix/thread.rs:90
  24: start_thread (0x7f32b19416da)
  25: __clone (0x7f32b145288e)
  26: <unknown> (0x0)

Thread 'ImportQueueWorker' panicked at 'Storage root must match that calculated.', /home/ens/.cargo/git/checkouts/substrate-7e08433d4c370a21/edf2a8f/srml/executive/src/lib.rs:214

This is a bug. Please report it at:

        https://github.com/airalab/substrate-node-robonomics/issues

2019-02-20 00:01:22 Failed to write to trie: Database missing expected key: 0xf0cea27e7a7819b8823186501a2df6e1496766cc5595f8561a2848045030caea
Hash not equal
df2ac7b2347cfdafe5509dc331e401c597ab8f8cbbb2b86854ea45944cd3fa88
36fc2dcf1eb77663026faa674dddb9db8a991f167887fdb470fbeda83039e84f
/home/akru/.cargo/git/checkouts/substrate-7e08433d4c370a21/edf2a8f/srml/executive/src/lib.rs
214
3
2019-02-20 00:01:23 Idle (2 peers), best: #3235 (0x7aea…502b), finalized #3235 (0x7aea…502b), ⬇ 7.5kiB/s ⬆ 0.5kiB/s

**Comment by akru** [comment]
Looks like something broken in db state, could you drop db an start sync again?

**Comment by ensrationis** [comment]
Fixed, when I deleted all files in "robonomics_testnet" folder with `rm -rf ~/.local/share/robonomics/chains/robonomics_testnet/`. Before I just delete db folder in "robonomics_testnet" folder.
